# Makefile for 
# Copyright (C) 2003 Greg Franks <greg@sce.carleton.ca>
# $Header$
# $Log$
# Revision 1.1  2003/03/12 02:10:53  greg
# Add makefiles.
#

SRVN=		parasrvn -A5e5
OPTS=

include ../Makefile
