# Makefile for 
# Copyright (C) 2003 Greg Franks <greg@sce.carleton.ca>
# $Header$
# $Log$
# Revision 1.2  2003/06/20 03:19:37  greg
# Add Te Kai Lu's model
#
# Revision 1.1  2003/03/12 02:10:53  greg
# Add makefiles.
#

SRVN=		lqns -zovertaking -Pvariance=srvn
OPTS=

include ../Makefile
