/* -*- c++ -*-
 * $Id: glblerr.cpp 13683 2020-07-13 14:25:00Z greg $
 *
 * Error messages common to solvers.
 *
 * Copyright the Real-Time and Distributed Systems Group,
 * Department of Systems and Computer Engineering,
 * Carleton University, Ottawa, Ontario, Canada. K1S 5B6
 *
 * December, 1995
 *
 * ----------------------------------------------------------------------
 */

#include "glblerr.h"

namespace LQIO {

    struct error_message_type global_error_messages[LSTGBLERRMSG+1] = {
        { RUNTIME_ERROR, "** NO ERROR **" },
        { FATAL_ERROR,   "Internal error." },                                                                                       /* FTL_INTERNAL_ERROR                   */
        { FATAL_ERROR,   "No more memory." },                                                                                       /* FTL_NO_MEMORY                        */
        { FATAL_ERROR,   "Model has no %s." },                                                                                      /* ERR_NO_OBJECT                        */
        { RUNTIME_ERROR, "%4.2f replies generated by entry \"%s\"." },                                                              /* ERR_NON_UNITY_REPLIES                */
        { RUNTIME_ERROR, "%s \"%s\" previously defined." },                                                                         /* ERR_DUPLICATE_SYMBOL                 */
        { RUNTIME_ERROR, "%s \"%s\": %s." },						                                            /* ERR_DOMAIN_ERROR			    */
        { RUNTIME_ERROR, "An error occurred while compiling the LQX program found in file: %s." },                                  /* ERR_LQX_COMPILATION                  */
        { RUNTIME_ERROR, "An error occurred executing the LQX program found in file: %s." },                                        /* ERR_LQX_EXECUTION                    */
	{ RUNTIME_ERROR, "Both LQX and SPEX found in file %s.  Use one or the other." },					    /* ERR_LQX_SPEX			    */
        { RUNTIME_ERROR, "Cannot open directory \"%s\" -- %s." },                                                                   /* ERR_CANT_OPEN_DIRECTORY,             */
        { RUNTIME_ERROR, "Cannot open file \"%s\" -- %s." },                                                                   	    /* ERR_CANT_OPEN_FILE, 	            */
        { RUNTIME_ERROR, "Cycle in activity graph for task \"%s\", backtrace is \"%s\"." },                                         /* ERR_CYCLE_IN_ACTIVITY_GRAPH          */
        { RUNTIME_ERROR, "Cycle in call graph,  backtrace is \"%s\"." },                                                            /* ERR_CYCLE_IN_CALL_GRAPH              */
        { RUNTIME_ERROR, "Data for %d phases specified.  Maximum permitted is %d." },                                               /* ERR_TOO_MANY_PHASES                  */
	{ RUNTIME_ERROR, "Decision %s has a decision type %s, which is not supported in this version." },                           /* ERR_INVALID_DECISION_TYPE            */
	{ RUNTIME_ERROR, "DecisionPath %s has an invalid decision path type, %s." },                                                /* ERR_INVALID_DECISION_PATH_TYPE       */ 
        { RUNTIME_ERROR, "Destination entry \"%s\" must be different from source entry \"%s\"." },                                  /* ERR_SRC_EQUALS_DST                   */
        { RUNTIME_ERROR, "Element \"%s\", missing attribute: \"%s\"."},		                                                    /* ERR_MISSING_ATTRIBUTE                */
	{ RUNTIME_ERROR, "Element \"%s\", unexpected attribute: \"%s\"." },							    /* ERR_UNEXPECTED_ATTRIBUTE		    */
	{ RUNTIME_ERROR, "Element \"%s\", invalid argument to attribute: \"%s\"." },						    /* ERR_INVALID_ARGUMENT		    */
        { RUNTIME_ERROR, "Entry \"%s\" accepts both rendezvous and send-no-reply messages." },                                      /* ERR_OPEN_AND_CLOSED_CLASSES          */
        { RUNTIME_ERROR, "Entry \"%s\" has invalid forwarding probability of %g." },                                                /* ERR_INVALID_FORWARDING_PROBABILITY   */
        { RUNTIME_ERROR, "Entry \"%s\" is not part of task \"%s\"."},                                                               /* ERR_WRONG_TASK_FOR_ENTRY             */
        { RUNTIME_ERROR, "Entry \"%s\" is not specified." },                                                                        /* ERR_ENTRY_NOT_SPECIFIED              */
        { RUNTIME_ERROR, "Entry \"%s\" must reply; the reply is not specified in the activity graph." },                            /* ERR_REPLY_NOT_GENERATED              */
        { RUNTIME_ERROR, "Entry \"%s\" specified as both a signal and a wait." },                                                   /* ERR_MIXED_SEMAPHORE_ENTRY_TYPES      */
        { RUNTIME_ERROR, "Entry \"%s\" specified as both a lock and a unlock." },                                                   /* ERR_MIXED_RWLOCK_ENTRY_TYPES         */
        { RUNTIME_ERROR, "Entry \"%s\" specified using both activity and phase methods." },                                         /* ERR_MIXED_ENTRY_TYPES                */
        { RUNTIME_ERROR, "External variables are present in file \"%s\", but there is no LQX program to resolve them." },           /* ERR_LQX_VARIABLE_RESOLUTION          */
        { RUNTIME_ERROR, "Fewer entries defined (%d) than tasks (%d)" },                                                            /* ERR_LESS_ENTRIES_THAN_TASKS          */
        { RUNTIME_ERROR, "Group \"%s\" has no tasks."  },                                                                           /* ERR_NO_TASK_DEFINED_FOR_GROUP        */
        { RUNTIME_ERROR, "Group \"%s\" has invalid share of %g."},                                                                  /* ERR_INVALID_SHARE                    */
        { RUNTIME_ERROR, "Integer value expected, actual value is %g." },                                                           /* ERR_NON_INTEGER                      */
        { RUNTIME_ERROR, "Integer value expected from \"%s\", actual value is %g." },                                               /* ERR_NON_INTEGER_EXPRESSION           */
        { RUNTIME_ERROR, "Invalid calls from %s \"%s\" %s \"%s\" to entry \"%s\": %s." },	                                    /* ERR_INVALID_CALL_PARAMETER	    */
        { RUNTIME_ERROR, "Invalid forwarding from entry \"%s\" to entry \"%s\": %s." },	                                            /* ERR_INVALID_FWDING_PARAMETER	    */
        { RUNTIME_ERROR, "Invalid lower range value for histogram of %g." },                                                        /* ERR_HISTOGRAM_INVALID_MIN            */
        { RUNTIME_ERROR, "Invalid path from fork \"%s\" for task \"%s\": backtrace is \"%s\"." },                                   /* ERR_JOIN_BAD_PATH                    */
        { RUNTIME_ERROR, "Invalid probability of %g." },                                                                            /* ERR_INVALID_PROBABILITY              */
        { RUNTIME_ERROR, "Invalid upper range value for histogram of %g." },                                                        /* ERR_HISTOGRAM_INVALID_MAX            */
        { RUNTIME_ERROR, "Invalid %s for %s \"%s\": %s." },					                         	    /* ERR_INVALID_PARAMETER		    */
        { RUNTIME_ERROR, "Name \"%s\" previously defined." },                                                                       /* ERR_MULTIPLY_DEFINED                 */
        { RUNTIME_ERROR, "No group specified for task \"%s\" running on processor \"%s\" using fair share scheduling." },           /* ERR_NO_GROUP_SPECIFIED               */
        { RUNTIME_ERROR, "No quantum is specified for processor \"%s\" with  \"%s\" scheduling."},                                  /* ERR_NO_QUANTUM_SCHEDULING            */
        { RUNTIME_ERROR, "No reference tasks have been specified in this model." },                                                 /* ERR_NO_REFERENCE_TASKS               */
        { RUNTIME_ERROR, "No signal or wait specified for semaphore task \"%s\"." },                                                /* ERR_NO_SEMAPHORE                     */
        { RUNTIME_ERROR, "No lock or unlock specified for rwlock task \"%s\"." },                                                   /* ERR_NO_RWLOCK                        */
        { RUNTIME_ERROR, "Non-reference task \"%s\" cannot have think time." },                                                     /* ERR_NON_REF_THINK_TIME               */
        { RUNTIME_ERROR, "Non-semaphore task \"%s\" cannot have a %s for entry \"%s\"." },                                          /* ERR_NOT_SEMAPHORE_TASK               */
        { RUNTIME_ERROR, "Non-rwlock task \"%s\" cannot have a %s for entry \"%s\"." },                                             /* ERR_NOT_RWLOCK_TASK                  */
        { RUNTIME_ERROR, "Number of %s is outside of program limits of (1,%d)." },                                                  /* ERR_TOO_MANY_X                       */
        { RUNTIME_ERROR, "Number of paths found to AND-Join \"%s\" for Task \"%s\" does not match fork list." },                    /* ERR_JOIN_PATH_MISMATCH               */
        { RUNTIME_ERROR, "OR branch probabilities for OR-Fork \"%s\" for task \"%s\" do not sum to 1.0; sum is %4.2f." },           /* ERR_MISSING_OR_BRANCH                */
        { RUNTIME_ERROR, "Parse error. %s." },                                                                                      /* ERR_PARSE_ERROR                      */
	{ RUNTIME_ERROR, "Precedence \"%s\" list previously defined." },							    /* ERR_DUPLICATE_X_LIST		    */
        { RUNTIME_ERROR, "Processor \"%s\" has invalid rate of %g." },                                                              /* ERR_INVALID_PROC_RATE                */
        { RUNTIME_ERROR, "Processor \"%s\" has no group." },                                                                        /* ERR_NO_GROUP_DEFINED_FOR_PR0CESSOR   */
        { RUNTIME_ERROR, "Range error converting \"%s\"." },                                                                        /* ERR_RANGE_ERROR                      */
        { RUNTIME_ERROR, "Reference task \"%s\", entry \"%s\" cannot forward requests." },                                          /* ERR_REF_TASK_FORWARDING              */
        { RUNTIME_ERROR, "Reference task \"%s\", entry \"%s\" cannot have open arrival stream." },                                  /* ERR_REFERENCE_TASK_OPEN_ARRIVALS     */
        { RUNTIME_ERROR, "Reference task \"%s\", entry \"%s\" receives requests." },                                                /* ERR_REFERENCE_TASK_IS_RECEIVER       */
        { RUNTIME_ERROR, "Reference task \"%s\", replies to entry \"%s\" from activity \"%s\"." },                                  /* ERR_REFERENCE_TASK_REPLIES           */
        { RUNTIME_ERROR, "Reference task \"%s\" must have a finite number of copies." },                                            /* ERR_REFERENCE_TASK_IS_INFINITE       */
        { RUNTIME_ERROR, "RW-lock task \"%s\" must have a positive number of concurrent readers." },                                /* ERR_RWLOCK_CONCURRENT_READERS        */
        { RUNTIME_ERROR, "Rwlock \"lock\" entry \"%s\" cannot accept send-no-reply requests." },                                    /* ERR_ASYNC_REQUEST_TO_LOCKENTRIES     */
        { RUNTIME_ERROR, "Semaphore \"wait\" entry \"%s\" cannot accept send-no-reply requests." },                                 /* ERR_ASYNC_REQUEST_TO_WAIT            */
        { RUNTIME_ERROR, "Start activity for entry \"%s\" is already defined.  Activity \"%s\" is a duplicate." },                  /* ERR_DUPLICATE_START_ACTIVITY         */
        { RUNTIME_ERROR, "Symbol \"%s\" not previously defined." },                                                                 /* ERR_NOT_DEFINED                      */
	{ RUNTIME_ERROR, "SPEX parameter \"%s\" cannot be used as observation \"%s\" for \"%s\"." },				    /* ERR_SPEX_PARAMETER_OBSERVATION 	    */
        { RUNTIME_ERROR, "Task \"%s\" cannot be an infinite server." },                                                             /* ERR_INFINITE_TASK                    */
        { RUNTIME_ERROR, "Task \"%s\" has %d entries defined, exactly %d are required." },                                          /* ERR_ENTRY_COUNT_FOR_TASK             */
        { RUNTIME_ERROR, "Task \"%s\" has activities but none are reachable." },                                                    /* ERR_NO_START_ACTIVITIES              */
        { RUNTIME_ERROR, "Task \"%s\" has no entries." },                                                                           /* ERR_NO_ENTRIES_DEFINED_FOR_TASK      */
        { RUNTIME_ERROR, "Task \"%s\", activity \"%s\" is a start activity." },                                                     /* ERR_IS_START_ACTIVITY                */
        { RUNTIME_ERROR, "Task \"%s\", activity \"%s\" is not specified."},                                                         /* ERR_ACTIVITY_NOT_SPECIFIED           */
        { RUNTIME_ERROR, "Task \"%s\", activity \"%s\" makes a duplicate reply for entry \"%s\"." },                                /* ERR_DUPLICATE_REPLY                  */
        { RUNTIME_ERROR, "Task \"%s\", activity \"%s\" makes invalid reply for entry \"%s\"." },                                    /* ERR_INVALID_REPLY                    */
        { RUNTIME_ERROR, "Task \"%s\", activity \"%s\" previously used in a fork." },                                               /* ERR_DUPLICATE_ACTIVITY_RVALUE        */
        { RUNTIME_ERROR, "Task \"%s\", activity \"%s\" previously used in a join." },                                               /* ERR_DUPLICATE_ACTIVITY_LVALUE        */
        { RUNTIME_ERROR, "Task \"%s\", activity \"%s\" replies to entry \"%s\" which does not accept rendezvous requests." },       /* ERR_REPLY_SPECIFIED_FOR_SNR_ENTRY    */
	{ RUNTIME_ERROR, "Task for entry \"%s\" has not been defined." },							    /* ERR_NO_TASK_FOR_ENTRY		    */
        { ADVISORY_ONLY, "Messages dropped at task \"%s\" for open-class queues." },                                                /* ADV_MESSAGES_DROPPED                 */
        { ADVISORY_ONLY, "No solve() call found in the lqx program in file: %s.  solve() was invoked implicitly." },                /* ADV_LQX_IMPLICIT_SOLVE               */
	{ ADVISORY_ONLY, "SPEX result variable \"%s\" was not defined." },							    /* ADV_SPEX_UNDEFINED_RESULT_VARIABLE   */
	{ ADVISORY_ONLY, "SPEX result variable \"%s\" was not previously used in an observation." },				    /* ADV_SPEX_UNUSED_RESULT_VARIABLE	    */
	{ ADVISORY_ONLY, "Too many dependent variables to plot from \"%s\" onwards." },						    /* ADV_TOO_MANY_GNUPLOT_VARIABLES	    */
        { WARNING_ONLY,  "%s \"%s\" %s \"%s\" makes zero (0) calls to entry \"%s\"." },                                             /* WRN_NO_CALLS_FOR                     */
        { WARNING_ONLY,  "%s \"%s\" is an infinite server with a multiplicity of %d." },                                            /* WRN_INFINITE_MULTI_SERVER            */
        { WARNING_ONLY,  "%s \"%s\" is not used." },                                                                                /* WRN_NOT_USED                         */
        { WARNING_ONLY,  "%s scheduling specified for %s \"%s\" is not supported." },                                               /* WRN_SCHEDULING_NOT_SUPPORTED         */
        { WARNING_ONLY,  "Entry \"%s\" does not receive any requests." },                                                           /* WRN_NO_REQUESTS_TO_ENTRY             */
        { WARNING_ONLY,  "Entry \"%s\" has no service time specified for any phase." },                                             /* WRN_NO_SERVICE_TIME                  */
	{ WARNING_ONLY,  "Entry \"%s\" attribute type=\"%s\" - entry type should be \"%s\"." },					    /* WRN_ENTRY_TYPE_MISMATCH		    */
	{ WARNING_ONLY,  "Invalid phase, %d, specified for SPEX result \"%%%s\" for entry \"%s\"." },				    /* WRN_INVALID_SPEX_RESULT_PHASE	    */
        { WARNING_ONLY,  "Processor \"%s\" using \"%s\" scheduling has a non-zero quantum specified." },                            /* WRN_QUANTUM_SCHEDULING               */
        { WARNING_ONLY,  "Number of %s defined (%d) does not match number specified (%d)." },                                       /* WRN_DEFINED_NE_SPECIFIED_X           */
        { WARNING_ONLY,  "Parameter is specified multiple times." },                                                                /* WRN_MULTIPLE_SPECIFICATION           */
        { WARNING_ONLY,  "%s \"%s\" %s \"%s\" has no service time specified." },                                                    /* WRN_NO_SERVICE_TIME_FOR              */
        { WARNING_ONLY,  "Group \"%s\" specified for processor \"%s\" which is not running fair share scheduling." },               /* WRN_NON_CFS_PR0CESSOR                */
        { WARNING_ONLY,  "Processor \"%s\" has no tasks." },                                                                        /* WRN_NO_TASKS_DEFINED_FOR_PROCESSOR   */
        { WARNING_ONLY,  "Queue length parameter not supported for task \"%s\"." },                                                 /* WRN_QUEUE_LENGTH                     */
        { WARNING_ONLY,  "Reference task \"%s\" does not send any messages." },                                                     /* WRN_NO_SENDS_FROM_REF_TASK           */
        { WARNING_ONLY,  "Reference task \"%s\" has more than one entry defined." },                                                /* WRN_TOO_MANY_ENTRIES_FOR_REF_TASK    */
        { WARNING_ONLY,  "Task \"%s\" with priority is running on processor \"%s\" which does not have priority scheduling." },     /* WRN_PRIO_TASK_ON_FIFO_PROC           */
        { RUNTIME_ERROR, "The %s feature is not supported in this version." },                                                      /* ERR_NOT_SUPPORTED                    */
    };                                                                                                                                                                     
}
